spring.application.name=attendance-management
# H2 Database
spring.datasource.url=jdbc:h2:mem:attendancedb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JWT Secret (keep this private!)
jwt.secret=attendance_super_secret_key_2026_do_not_share

# Server port
server.port=8080